### ISSUE TITLE
Finger usage of Swedish version

### ISSUE THREAD

**Issue by usand** [christianrosdahl/ahei-keyboard#1]
I'm currently learning the Swedish version and noticed that the recommended finger usage for the _number row_ is different from the English version. If this is by design, perhaps it could be clarified since I found it somewhat confusing. Or maybe the picture just needs fixing.

Minor quibbles aside, the layout looks really promising and I enjoyed reading the design considerations. :^)

**Comment by christianrosdahl** [comment]
Thanks for your feedback! I'm happy to hear that you are trying out the layout! I actually haven't paid attention to the finger usage on the number row, and have now added a clarifying remark about this. As I state there, the reason for the difference is that it was configured like that in the keyboard layout analyzer for the Dvorak variant and the Swedish QWERTY variant, respectively, which were my starting points. So it's not something that I have considered explicitly. Personally, I use the Swedish variant with the standard finger usage, so that's what I would recommend to start with.

**Comment by usand** [comment]
Thanks for clearing that up with the comment, I'm closing this issue. :)

**Comment by usand** [comment]
Thanks for clearing that up with the comment. :)
